Src/Acd.Web.Public/Controllers/StartPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using System.Web.Security;
using Acd.Web.Public.Models;
using N2;
using N2.Definitions;
using N2.Engine;
using N2.Engine.Globalization;
using N2.Persistence;
using N2.Persistence.Search;
using N2.Web;
using N2.Web.Mvc;
using N2Content = N2.Content;
namespace Acd.Web.Public.Controllers
{
    /// <summary>
    /// The registration <see cref="Registrations.StartPageRegistration"/> is responsible for
    /// connecting this controller to the start page model.
    /// </summary>
    public class StartPageController : ContentController<StartPage>
    {
        public ActionResult NotFound()
        {
            var closestMatch = Content.Traverse.Path(Request.AppRelativeCurrentExecutionFilePath.Trim('~', '/')).StopItem;

            var startPage = Content.Traverse.ClosestStartPage(closestMatch);
            var urlText = Request.AppRelativeCurrentExecutionFilePath.Trim('~', '/').Replace('/', ' ');
            var similarPages = GetSearchResults(startPage, urlText, 10).ToList();

            ControllerContext.RouteData.ApplyCurrentPath(new PathData(new ContentPage { Parent = startPage }));
            Response.TrySkipIisCustomErrors = true;
            Response.Status = "404 Not Found";

            return View(similarPages);
        }

        [ContentOutputCache]
        public ActionResult SiteMap()
        {
            var start = this.Content.Traverse.StartPage;
            var content = Tree.From(start)
                .Filters(N2Content.Is.Accessible(),
                    new N2.Collections.PageFilter(),
                    new N2.Collections.PublishedFilter(),
                    new N2.Collections.DelegateFilter(x =>
                    {
                        var destination = x.GetDetail<string>("Destination", null);
                        return string.IsNullOrWhiteSpace(destination);
                    }),
                    new N2.Collections.DelegateFilter(x =>
                    {
                        var excluded = x.GetDetail("ExcludeFromSiteMap", false);
                        return !excluded;
                    }))
                .ExcludeRoot(true).ToString();
            return Content("<ul>"
                + "<li>" + Link.To(start) + "</li>"
                + content + "</ul>");
        }

        public ActionResult Search(string q)
        {
            if (string.IsNullOrWhiteSpace(q))
                return Content("<ul><li>A search term is required</li></ul>");

            var hits = GetSearchResults(CurrentPage ?? this.Content.Traverse.StartPage, q, 50);

            var results = new StringBuilder();
            HashSet<ContentPage> appendedPages = new HashSet<ContentPage>();
            foreach (var hit in hits)
            {
                var page = hit as ContentPage;
                if (page == null)
                {
                    // Probably hit a part...
                    page = this.Content.Traverse.ClosestPage(hit) as ContentPage;
                }

                if (page == null || appendedPages.Contains(page))
                    continue;

                appendedPages.Add(page);
            }

            foreach (var page in appendedPages.Where(p => p.Title.IndexOf(q, StringComparison.OrdinalIgnoreCase) >= 0).ToList())
            {
                appendedPages.Remove(page);
                AppendPage(results, page);
            }

            foreach (var page in appendedPages.Where(p => p.Summary.IndexOf(q, StringComparison.OrdinalIgnoreCase) >= 0).ToList())
            {
                appendedPages.Remove(page);
                AppendPage(results, page);
            }

            foreach (var page in appendedPages.ToList())
            {
                appendedPages.Remove(page);
                AppendPage(results, page);
            }

            if (results.Length == 0)
                return Content("<ul><li>No hits</li></ul>");

            return Content("<ul>" + results + "</ul>");
        }

        private void AppendPage(StringBuilder results, ContentPage page)
        {
            results.Append("<li>")
                .Append(Link.To(page))
                .Append("</li>");
        }

        private IEnumerable<ContentItem> GetSearchResults(ContentItem root, string text, int take)
        {
            var query = Query.For(text).Below(root).ReadableBy(User, Roles.GetRolesForUser).Except(Query.For(typeof(ISystemNode)));
            var hits = Engine.Resolve<IContentSearcher>().Search(query).Hits.Select(h => h.Content);
            return hits;
        }

        [ContentOutputCache]
        public ActionResult Translations(int id)
        {
            var sb = new StringBuilder();

            var item = Engine.Persister.Get(id);
            var lg = Engine.Resolve<LanguageGatewaySelector>().GetLanguageGateway(item);
            var translations = lg.FindTranslations(item);
            foreach (var language in translations)
                sb.Append("<li>").Append(Link.To(language).Text(lg.GetLanguage(language).LanguageTitle)).Append("</li>");

            if (sb.Length == 0)
                return Content("<ul><li>This page is not translated</li></ul>");

            return Content("<ul>" + sb + "</ul>");
        }
    }

    [Service(typeof(IContentSearcher))]
    [Service(typeof(ILightweightSearcher))]
    public class CustomFindingContentSearcher : IContentSearcher, ILightweightSearcher
    {
        private IContentItemRepository repository;
        //IItemFinder finder;

        //public FindingContentSearcher(IItemFinder finder)
        public CustomFindingContentSearcher(IContentItemRepository repository)
        {
            //this.finder = finder;
            this.repository = repository;
        }

        #region ITextSearcher Members

        /// <summary>Searches for items below an ancestor that matches the given query.</summary>
        /// <param name="ancestor">The ancestor below which the results should be found.</param>
        /// <param name="query">The query text.</param>
        /// <param name="skip">A number of items to skip.</param>
        /// <param name="take">A number of items to take.</param>
        /// <returns>An enumeration of items matching the search query.</returns>
        public IEnumerable<ContentItem> Search(string ancestor, string query, int skip, int take, bool? onlyPages, string[] types, out int totalRecords)
        {
            var q = new ParameterCollection();
            if (ancestor != null)
            {
                q.Add(Parameter.Like("AncestralTrail", ancestor + "%"));// & Parameter.IsNotNull("Title"));
            }

            if (!string.IsNullOrEmpty(query))
            {
                var words = query.Split(' ').Where(w => w.Length > 0).Select(w => "%" + w.Trim('*') + "%");
                q.Add(new ParameterCollection(Operator.Or, words.Select(word => (Parameter.Like("Title", word) | Parameter.Like(null, word).Detail()))));
            }

            if (onlyPages.HasValue)
                if (onlyPages.Value)
                    q.Add(Parameter.IsNull("ZoneName"));
                else
                    q.Add(Parameter.IsNotNull("ZoneName"));

            if (types != null)
                q.Add(Parameter.In("class", types));

            totalRecords = (int)repository.Count(q);
            return repository.Find(q.Skip(skip).Take(take));

            //var q = finder.Where.AncestralTrail.Like(ancestor + "%")
            //	.And.Title.IsNull(false);

            //var words = query.Split(' ').Where(w => w.Length > 0).Select(w => "%" + w.Trim('*') + "%");
            //foreach (var word in words)
            //{
            //	q = q.And.OpenBracket()
            //		.Title.Like(word)
            //		.Or.Detail().Like(word)
            //	.CloseBracket();
            //}
            //if (onlyPages.HasValue)
            //	q = q.And.OpenBracket()
            //		.ZoneName.IsNull(onlyPages.Value)
            //		.Or.ZoneName.Eq("")
            //	.CloseBracket();
            //if (types != null)
            //	q = q.And.Property("class").In(types);

            //totalRecords = q.Count();
            //return q.FirstResult(skip).MaxResults(take).Select();
        }

        public Result<ContentItem> Search(Query query)
        {
            var result = new Result<ContentItem>();
            int total;
            result.Hits = Search(query.Ancestor, query.Text, query.SkipHits, query.TakeHits, query.OnlyPages, query.Types, out total)
                .Select(i => new Hit<ContentItem> { Title = i.Title, Url = i.Url, Content = i, Score = (i.Title != null && query.Text != null && i.Title.ToLower().Contains(query.Text.ToLower())) ? 1 : .5 });
            result.Total = total;
            return result;
        }

        #endregion

        Result<LightweightHitData> ISearcher<LightweightHitData>.Search(Query query)
        {
            var result = Search(query);
            return new Result<LightweightHitData>
            {
                Count = result.Count,
                Total = result.Total,
                Hits = result.Hits.Select(h => new Hit<LightweightHitData>
                {
                    Score = h.Score,
                    Title = h.Title,
                    Url = h.Url,
                    Content = new LightweightHitData
                    {
                        ID = h.Content.ID,
                        AlteredPermissions = h.Content.AlteredPermissions,
                        AuthorizedRoles = h.Content.AuthorizedRoles.Any() ? h.Content.AuthorizedRoles.Select(ar => ar.Role).ToArray() : new[] { "Everyone" },
                        State = h.Content.State,
                        Visible = h.Content.Visible,
                        Path = h.Content.Path
                    }
                }).ToList()
            };
        }
    }
}

Src/Acd.Web.Public/Views/Shared/LayoutPartials/AlertWrap.cshtml
<div class="cookie-alert-wrap" style="display: none;">
    <div class="cookie-alert">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-8">
                    <div class="alert-text">You have a saved incomplete form, would you like to continue?</div>

                </div>
                <div class="col-sm-6 col-md-4">
                    <a class="btn btn-default close-alert" href="">No thanks</a>
                    @{
                        var page = N2.Find.Items.Where.Type.Eq(typeof(Acd.Web.Public.Models.OnlineFormPage))
                            .Filters(new N2.Collections.PublishedFilter())
                            .Select().FirstOrDefault();
                        var url = page == null ? "#" : page.Url;
                    }
                    <a class="btn btn-default continue" href="@url">Continue</a>
                </div>
            </div>
        </div>
    </div>
</div>

Src/Acd.Web.Public/Views/Shared/LayoutPartials/Breadcrumb.cshtml
@using Acd.Web.Public.Models
@{
    var showBreadcrumb = false;
    if (Content.Current.Page is ContentPage)
    {
        showBreadcrumb = (Content.Current.Page as ContentPage).ShowBreadcrumb;
    }
    if (!showBreadcrumb)
    {
        return;
    }
    var start = Content.Traverse.StartPage;
    var currentItem = Content.Current.Item;
    var breadcrumbs = Find.EnumerateParents(currentItem, start, true).ToList();
    breadcrumbs.Reverse();
    if (!breadcrumbs.Any())
    {
        return;
    }
}

<div class="row">
    <div class="col-sm-12 col-md-8 col-md-offset-3">
        <div class="bread">
            @foreach (var crumb in breadcrumbs)
            {
                if (crumb != currentItem)
                {
                <a href="@crumb.Url">@crumb.Title</a><span class="bread-separator"></span>
                }
                else
                {
                <span>@crumb.Title</span>
                }
            }
        </div>
    </div>
</div>

Src/Acd.Web.Public/Views/Shared/LayoutPartials/Content.cshtml
@*@if (!string.IsNullOrEmpty(Content.Data.Image))
{
    <figure class="page-image">
        <img src="@Content.Data.Image" class="img-@Content.Data.ImageDisplayType.ToString().ToLower()" alt="@Content.Data.Title" />
    </figure>
}*@

@Content.Display.Text

Src/Acd.Web.Public/Views/Shared/LayoutPartials/Footer.cshtml
<div class="container">
    <div class="row">
        @{
            var isOutOfStructure = Content.Current.Item == null && !string.IsNullOrEmpty(Request["returnUrl"]);
            using (isOutOfStructure ? Content.BeginScope(Request["returnUrl"]) : Content.BeginScope(Content.Traverse.StartPage))
            {
                @Content.Display.FooterText
            }
        }
    </div>

    <div class="row">
        <div class="footer-links-all">
            <div class="col-sm-12 col-md-12 col-lg-12">

                @{ Html.RenderPartial("LayoutPartials/FooterNavigation"); }
            </div>
        </div>
    </div>

    <div class="row">
        <div class="footer-links">
            <div class="col-sm-12 col-md-12 col-lg-12">

                @{
                    var footerLinks = N2.Find.Items.Where.Type.Eq(typeof(Acd.Web.Public.Models.ContentPage)).Select<Acd.Web.Public.Models.ContentPage>().Where(x => x.VisibleFooter).ToList();

                    if (footerLinks.Any())
                    {
                        var home = footerLinks.FirstOrDefault(x => x.Url.Equals("/") || x.Url.Equals("/home"));
                        var links= footerLinks.Where(x => !(x.Url.Equals("/") || x.Url.Equals("/home"))).OrderBy(x => x.Title).ToList();
                        if (home != null)
                        {
                            links.Insert(0, home);
                        }
                        <ul class="list-inline">
                            @foreach (var item in links)
                            {
                                <li>
                                    <a class="" href="@item.Url">@item.Title</a>
                                </li>
                            }
                        </ul>
                    }
                }
            </div>
        </div>
    </div>



</div>
<!-- /container -->

Src/Acd.Web.Public/Views/Shared/LayoutPartials/FooterNavigation.cshtml
@{
    var currentPage = N2.Find.CurrentPage;
    var parents = N2.Find.Parents.ToList();
    if (currentPage != null)
    {
        parents.Add(currentPage);
    }
    var startPage = N2.Content.Traverse.StartPage;
    var roots = startPage.GetChildren(new N2.Collections.PageFilter(),
                new N2.Collections.AccessFilter(),
                new N2.Collections.PublishedFilter(),
                new N2.Collections.NavigationFilter());
}
<div class="row">
    @{
        foreach (var root in roots)
        {
            var active = parents.Count(x => x.ID == root.ID) > 0;
            var children = root.GetChildren(new N2.Collections.PageFilter(),
            new N2.Collections.AccessFilter(),
            new N2.Collections.PublishedFilter(),
            new N2.Collections.NavigationFilter());
            bool subnav = children.Any();
            <div class="col-sm-2">

                <h2 class="menu-item @(active ? "current" : null) @(subnav ? "has-subs" : null)"><a href="@root.Url" class="lev-one">@root.Title</a></h2>
                @{
            if (children.Any())
            {
                <ul class="footer-subnav hidden-xs hidden-sm">
                    @{
                foreach (var child in children)
                {
                    <li class="menu-item"><a href="@child.Url">@child.Title</a></li>
                }
                    }
                </ul>
            }
                }

            </div>
        }
    }
</div>

Src/Acd.Web.Public/Views/Shared/LayoutPartials/Header.cshtml
<div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8">
          @{Html.RenderPartial("LayoutPartials/Logotype");}
          <h3 style="color: #3C6E8F; padding-left: 40px;">What do you need to know?</h3>
      </div>
    	<div class="nav-mob-row clearfix" style="border: none;">
	        <div class="col-sm-4 hidden-mobile">
                @{
                    Html.DroppableZone("TopRecursive").Title("Top Recursive").Render();
                }
	        </div>
    	</div>
    </div>
</div>

Src/Acd.Web.Public/Views/Shared/LayoutPartials/HomeHeader.cshtml
<div class="header" id="header">
    <div class="container">
        <div class="row">
            <div class="col-xs-8">
                @{
                    var startPage = Content.Traverse.StartPage;
                    var logoUrl = startPage.GetDetail<string>("HomepageLogo", null);
                }
                <a href="/" class="logo-url">
                    <img src="@logoUrl" class="img-responsive" alt="24Legal logo" /></a>
                <h3 style="color: #3C6E8F; padding-left: 40px;">What do you need to know?</h3>
            </div>

            <div class="col-xs-4 hidden-mobile">
                @{
                    Html.DroppableZone("TopRecursive").Title("Top Recursive").Render();
                }
            </div>
        </div>

    </div>
</div>
@{
    var fullmenu = startPage.GetDetail<bool>("FullMenuOnHomePage", false);
}
@if (fullmenu)
{
    Html.RenderPartial("LayoutPartials/TopNavigation");
}
else
{
    Html.RenderPartial("LayoutPartials/HomeTopNavigation");
}

Src/Acd.Web.Public/Views/Shared/LayoutPartials/HomeTopNavigation.cshtml
<div class="header-nav home">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-7 col-lg-8">
                <div>
                    @*@{Html.RenderAction("Status", "Membership");}*@
                </div>
            </div>
            <div class="col-sm-6 col-md-5 col-lg-4" id="nav-outer">
                @{
                    var currentPage = N2.Find.CurrentPage;
                    var parents = N2.Find.Parents.ToList();
                    if (currentPage != null)
                    {
                        parents.Add(currentPage);
                    }

                    var roots = Content.Traverse.StartPage.GetChildren(new N2.Collections.PageFilter(),
                                new N2.Collections.AccessFilter(),
                                new N2.Collections.PublishedFilter())
                                .Where(x => x.GetDetail<bool>("ShowInStartpage", false) == true);
                }
                <ul class="sf-menu collapse pull-right-bak" id="nav">
                    @{Html.RenderPartial("LayoutPartials/SliderMenuItems");}
                    @{
                        foreach (var root in roots)
                        {
                            var active = parents.Count(x => x.ID == root.ID) > 0;
                            <li class="menu-item @(active ? "current" : null)">
                                <a href="@root.Url">@root.Title</a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
</div>

Src/Acd.Web.Public/Views/Shared/LayoutPartials/Logotype.cshtml
@using (Content.BeginScope(Content.Traverse.StartPage))
{
    Content.Render.Displayable(
           new N2.Details.DisplayableImageAttribute { Name = "Logotype", PreferredSize = null, CssClass = "img-responsive",Alt="Advance Care Directives logo" })
           .Wrap(@<a href="@Content.Current.Item.Url" class="home-logo">@item.RenderContents()</a>).Render(); 
}

Src/Acd.Web.Public/Views/Shared/LayoutPartials/Search.cshtml
@{
    var isHome = false;
    if (N2.Find.CurrentPage == N2.Find.StartPage)
    {
        isHome = true;
    }
}

<div class="@(isHome ? "col-md-12" : "col-sm-3 col-sm-push-1")" id="search-outer">
    @Html.Raw(isHome ? "<div class='row'>" : null)
    <div class="search-wrap @(isHome ? "home" : null)">
        @using (Html.BeginForm("Search", "StartPage", FormMethod.Get, new { id = "searchform", role = "search" }))
        {
            <label for="searchFormInput" style="display:none;">Search Site</label>
            <input type="text" id="searchFormInput" name="q" placeholder="Search site" class="search-site">
            <button type="submit" class="roundbox search-btn">Search</button>
        }
    </div>
    @Html.Raw(isHome ? "</div>" : null)
</div>

Src/Acd.Web.Public/Views/Shared/LayoutPartials/SliderMenuItems.cshtml
@{
    var startPage = Content.Traverse.StartPage;
    var flexSlider = startPage.GetChildren(
        new N2.Collections.DelegateFilter(x => x.TemplateKey == "FlexSlider"),
        new N2.Collections.PublishedFilter()).FirstOrDefault();

    if (flexSlider == null)
    {
        return;
    }

    var sliderItems = flexSlider.GetChildren(
        new N2.Collections.ZoneFilter("SliderArea"),
        new N2.Collections.PublishedFilter());
    var items = new List<ContentItem>();
    foreach (var sliderItem in sliderItems)
    {
        using (Content.BeginScope(sliderItem))
        {
            var heroItems = Content.Current.Item.GetChildren(
                new N2.Collections.ZoneFilter("HeroArea"),
                new N2.Collections.PublishedFilter());
            foreach (var heroItem in heroItems)
            {
                using (Content.BeginScope(heroItem))
                {
                    <li class="menu-item">
                        <a href="@Content.Data.LinkTarget" class="lev-one">@Content.Data.Title</a>
                    </li>
                }
            }
        }
    }
}

Src/Acd.Web.Public/Views/Shared/LayoutPartials/SubNavigation.cshtml
@{
    var startPage = Content.Traverse.StartPage;
    var currentPage = Content.Current.Page;
    var parents = N2.Find.EnumerateParents(currentPage, startPage, true);
    var root = parents.Skip(parents.Count() - 2).FirstOrDefault();
    if (root == null)
    {
        return;
    }
    var children = root.GetChildren(new N2.Collections.NavigationFilter());
}
<ul class="nav">
    @foreach (var child in children)
    {
        var grandchildren = child.GetChildren(new N2.Collections.NavigationFilter());
        var active = parents.Any(x => x.ID == child.ID);

        <li class="@(active ? "active" : null)">
            @Html.Link(child)
        @if (active && grandchildren.Count > 0)
        {
            <ul class="nav">
                @foreach (var grandchild in grandchildren)
                {
                    active = parents.Any(x => x.ID == grandchild.ID);
                    <li class="@(active ? "active" : null)">@Html.Link(grandchild)</li>
                }
            </ul>
        }
    </li>
    }
</ul>

Src/Acd.Web.Public/Views/Shared/LayoutPartials/Title.cshtml
@{
    var showPageTitle = Content.Current.Page.GetDetail("ShowPageTitle", true);

    //if (Content.Has.ShowPageTitle && Content.Data.ShowPageTitle)
    //{
    //    showPageTitle = Content.Data.ShowPageTitle;
    //}
    if (!showPageTitle && !string.IsNullOrWhiteSpace(Request.QueryString["ShowPageTitle"]))
    {
        showPageTitle = true;
    }

    if (!showPageTitle)
    {
        return;
    }

    var title = Content.Data.Title;
    if(string.IsNullOrWhiteSpace(title)){
        title = ViewBag.Title;
    }
}
<div class="row">
    <div class="col-sm-12 col-md-8 col-md-offset-3">
        <h1 class="page-heading">@title</h1>
    </div>
</div>

Src/Acd.Web.Public/Views/Shared/LayoutPartials/TopNavigation.cshtml
<div class="header-nav">
	<div class="container">
	    <div class="row">
	        <div class="col-sm-12 col-md-12" id="nav-outer">
	            @{
	                var currentPage = N2.Find.CurrentPage;
	                var parents = N2.Find.Parents.ToList();
	                if (currentPage != null)
	                {
	                    parents.Add(currentPage);
	                }
	                var startPage = N2.Content.Traverse.StartPage;
	                var roots = startPage.GetChildren(new N2.Collections.PageFilter(),
	                            new N2.Collections.AccessFilter(),
	                            new N2.Collections.PublishedFilter(),
	                            new N2.Collections.NavigationFilter());
	            }
	            <ul class="sf-menu collapse" id="nav">
	                @{Html.RenderPartial("LayoutPartials/SliderMenuItems");}
	                @{
	                    foreach (var root in roots)
	                    {
	                        var active = parents.Count(x => x.ID == root.ID) > 0;
	                        var children = root.GetChildren(new N2.Collections.PageFilter(),
	                            new N2.Collections.AccessFilter(),
	                            new N2.Collections.PublishedFilter(),
	                            new N2.Collections.NavigationFilter());
	                        bool subnav = children.Any();
	                        <li class="menu-item @(active ? "current" : null) @(subnav ? "has-subs" : null)">
	                            <a href="@root.Url" class="lev-one">@root.Title</a>
	                            @{
	                                if (children.Any())
	                                {
	                                    <ul class="subnav collapse">
	                                        @{
	                                            foreach (var child in children)
	                                            {
	                                                <li class="menu-item"><a href="@child.Url">@child.Title</a></li>
	                                            }
	                                        }
	                                    </ul>
	                                }
	                            }
	                        </li>
	                    }
	                }
	            </ul>
	        </div>
	    </div>
	</div>
</div>